### ISSUE TITLE
Not implemented scorer

### ISSUE THREAD

**Issue by okkez** [ranguba/groonga-client#25]
http://groonga.org/ja/docs/reference/commands/select.html#select-scorer

**Comment by komainu8** [comment]
Is the below scorer's interface fit your purpose?

exsample)
call : 
`select.scorer( "age == %{value}", :value => 29 )`

return : 
`{
  :table => "table_name",
  :scorer => "age => 29"
}`

**Comment by kou** [comment]
`scorer` is normally `_score = ...` style. So `"age == %{value}"` example is strange.

How about the following API?

```ruby
select.scorer(:age) # => select --scorer '_score = age'
select.scorer("-geo_distance(%{column}, %{point})", column: :location, point: "35.68138194x139.766083888889")
  # => select --scorer '_score = -geo_distance(location, "35.68138194x139.766083888889")'
select.scorer("_score = %{column}", column: :age) # =>  select --scorer '_score = age'
```
```

**Comment by komainu8** [comment]
Thnak you for your comment.
I could understand how to use `scorer` parameter. I'll implements on your advice.
