### ISSUE TITLE
Support Cool.io?

### ISSUE THREAD

**Issue by KitaitiMakoto** [ranguba/groonga-client#3]
Hi,

I think about patch for HTTP Basic Authentication feature to this library and am reading code and then found that this lib supports Cool.io. It uses `Coolio::HttpClient` removed at v1.3.0(See https://github.com/tarcieri/cool.io/blob/master/CHANGES.md#130).

Of course, we can use `Groonga::Client::Protocol::HTTP::Coolio` when we use Cool.io < v1.3.0. Do you keep to support Cool.io?

I'm asking to determine I should write patch to `Groonga::Client::Protocol::HTTP::Coolio` as well as `Groonga::Client::Protocol::HTTP::Synchronous`.

Thank you.

**Comment by kou** [comment]
We keep to support Cool.io.

But you don't need to write a patch for Cool.io backend. You can care only about `Synchronous`.

**Comment by KitaitiMakoto** [comment]
Thank you for reply.
Okay, I will start writing patch to `Synchronous`.
